apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment1
  labels:
    app: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: goapp
          image: ghcr.io/ravilkr14/goapp:1
          ports:
          - containerPort: 8080
      imagePullSecrets:
          - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: goapp-service1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: goapp
  type: NodePort
